export const FETCH_CART_REQUEST = 'FETCH_CART_REQUEST'
export const FETCH_CART_SUCCESS = 'FETCH_CART_SUCCESS'
export const FETCH_CART_FAILURE = 'FETCH_CART_FAILURE'

export const ADD_TO_CART_REQUEST = 'ADD_TO_CART_REQUEST'
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS'
export const ADD_TO_CART_FAILURE = 'ADD_TO_CART_FAILURE'

export const FETCH_ACCOUNT_REQUEST = 'FETCH_ACCOUNT_REQUEST'
export const FETCH_ACCOUNT_SUCCESS = 'FETCH_ACCOUNT_SUCCESS'
export const FETCH_ACCOUNT_FAILURE = 'FETCH_ACCOUNT_FAILURE'

export const FETCH_AUTHENTICITY_TOKEN_REQUEST = 'FETCH_AUTHENTICITY_TOKEN_REQUEST'
export const FETCH_AUTHENTICITY_TOKEN_SUCCESS = 'FETCH_AUTHENTICITY_TOKEN_SUCCESS'
export const FETCH_AUTHENTICITY_TOKEN_FAILURE = 'FETCH_AUTHENTICITY_TOKEN_FAILURE'

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST'
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS'
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE'
export const CLEAR_PRODUCTS = 'CLEAR_PRODUCTS'

export const FETCH_PRODUCT_REQUEST = 'FETCH_PRODUCT_REQUEST'
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS'
export const FETCH_PRODUCT_FAILURE = 'FETCH_PRODUCT_FAILURE'
export const CLEAR_PRODUCT = 'CLEAR_PRODUCT'

export const ADD_ALERT = 'ADD_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'

export const CREATE_STRIPE_TOKEN_REQUEST = 'CREATE_STRIPE_TOKEN_REQUEST'
export const CREATE_STRIPE_TOKEN_SUCCESS = 'CREATE_STRIPE_TOKEN_SUCCESS'
export const CREATE_STRIPE_TOKEN_FAILURE = 'CREATE_STRIPE_TOKEN_FAILURE'
